Number of Steps: 2001
Number of States: 10
Reading traj = 0 of 50
Reading traj = 1 of 50
Reading traj = 2 of 50
Reading traj = 3 of 50
Reading traj = 4 of 50
Reading traj = 5 of 50
Reading traj = 6 of 50
Reading traj = 7 of 50
Reading traj = 8 of 50
Reading traj = 9 of 50
Reading traj = 10 of 50
Reading traj = 11 of 50
Reading traj = 12 of 50
Reading traj = 13 of 50
Reading traj = 14 of 50
Reading traj = 15 of 50
Reading traj = 16 of 50
Reading traj = 17 of 50
Reading traj = 18 of 50
Reading traj = 19 of 50
Reading traj = 20 of 50
Reading traj = 21 of 50
Reading traj = 22 of 50
Reading traj = 23 of 50
Reading traj = 24 of 50
Reading traj = 25 of 50
Reading traj = 26 of 50
Reading traj = 27 of 50
Reading traj = 28 of 50
Reading traj = 29 of 50
Reading traj = 30 of 50
Reading traj = 31 of 50
Reading traj = 32 of 50
Reading traj = 33 of 50
Reading traj = 34 of 50
Reading traj = 35 of 50
Reading traj = 36 of 50
Reading traj = 37 of 50
Reading traj = 38 of 50
Reading traj = 39 of 50
Reading traj = 40 of 50
Reading traj = 41 of 50
Reading traj = 42 of 50
Reading traj = 43 of 50
Reading traj = 44 of 50
Reading traj = 45 of 50
Reading traj = 46 of 50
Reading traj = 47 of 50
Reading traj = 48 of 50
Reading traj = 49 of 50
Calculating Hamiltonian 0 of 46 averages with 50 trajectories
Calculating Hamiltonian 1 of 46 averages with 50 trajectories
Calculating Hamiltonian 2 of 46 averages with 50 trajectories
Calculating Hamiltonian 3 of 46 averages with 50 trajectories
Calculating Hamiltonian 4 of 46 averages with 50 trajectories
Calculating Hamiltonian 5 of 46 averages with 50 trajectories
Calculating Hamiltonian 6 of 46 averages with 50 trajectories
Calculating Hamiltonian 7 of 46 averages with 50 trajectories
Calculating Hamiltonian 8 of 46 averages with 50 trajectories
Calculating Hamiltonian 9 of 46 averages with 50 trajectories
Calculating Hamiltonian 10 of 46 averages with 50 trajectories
Number of Steps: 2001
Number of States: 10
Reading traj = 0 of 50
Reading traj = 1 of 50
Reading traj = 2 of 50
Reading traj = 3 of 50
Reading traj = 4 of 50
Reading traj = 5 of 50
Reading traj = 6 of 50
Reading traj = 7 of 50
Reading traj = 8 of 50
Reading traj = 9 of 50
Reading traj = 10 of 50
Reading traj = 11 of 50
Reading traj = 12 of 50
Reading traj = 13 of 50
Reading traj = 14 of 50
Reading traj = 15 of 50
Reading traj = 16 of 50
Reading traj = 17 of 50
Reading traj = 18 of 50
Reading traj = 19 of 50
Reading traj = 20 of 50
Reading traj = 21 of 50
Reading traj = 22 of 50
Reading traj = 23 of 50
Reading traj = 24 of 50
Reading traj = 25 of 50
Reading traj = 26 of 50
Reading traj = 27 of 50
Reading traj = 28 of 50
Reading traj = 29 of 50
Reading traj = 30 of 50
Reading traj = 31 of 50
Reading traj = 32 of 50
Reading traj = 33 of 50
Reading traj = 34 of 50
Reading traj = 35 of 50
Reading traj = 36 of 50
Reading traj = 37 of 50
Reading traj = 38 of 50
Reading traj = 39 of 50
Reading traj = 40 of 50
Reading traj = 41 of 50
Reading traj = 42 of 50
Reading traj = 43 of 50
Reading traj = 44 of 50
Reading traj = 45 of 50
Reading traj = 46 of 50
Reading traj = 47 of 50
Reading traj = 48 of 50
Reading traj = 49 of 50
Calculating Hamiltonian 0 of 41 averages with 50 trajectories
Calculating Hamiltonian 11 of 46 averages with 50 trajectories
Calculating Hamiltonian 12 of 46 averages with 50 trajectories
Calculating Hamiltonian 13 of 46 averages with 50 trajectories
Calculating Hamiltonian 14 of 46 averages with 50 trajectories
Calculating Hamiltonian 15 of 46 averages with 50 trajectories
Calculating Hamiltonian 16 of 46 averages with 50 trajectories
Calculating Hamiltonian 17 of 46 averages with 50 trajectories
Calculating Hamiltonian 18 of 46 averages with 50 trajectories
Calculating Hamiltonian 19 of 46 averages with 50 trajectories
Calculating Hamiltonian 20 of 46 averages with 50 trajectories
Calculating Hamiltonian 21 of 46 averages with 50 trajectories
Calculating Hamiltonian 1 of 41 averages with 50 trajectories
Calculating Hamiltonian 22 of 46 averages with 50 trajectories
Calculating Hamiltonian 23 of 46 averages with 50 trajectories
Calculating Hamiltonian 24 of 46 averages with 50 trajectories
Calculating Hamiltonian 25 of 46 averages with 50 trajectories
Calculating Hamiltonian 26 of 46 averages with 50 trajectories
Calculating Hamiltonian 27 of 46 averages with 50 trajectories
Calculating Hamiltonian 28 of 46 averages with 50 trajectories
Calculating Hamiltonian 29 of 46 averages with 50 trajectories
Calculating Hamiltonian 30 of 46 averages with 50 trajectories
Calculating Hamiltonian 31 of 46 averages with 50 trajectories
Calculating Hamiltonian 32 of 46 averages with 50 trajectories
Calculating Hamiltonian 33 of 46 averages with 50 trajectories
Calculating Hamiltonian 2 of 41 averages with 50 trajectories
Calculating Hamiltonian 34 of 46 averages with 50 trajectories
Calculating Hamiltonian 35 of 46 averages with 50 trajectories
Calculating Hamiltonian 36 of 46 averages with 50 trajectories
Calculating Hamiltonian 37 of 46 averages with 50 trajectories
Calculating Hamiltonian 38 of 46 averages with 50 trajectories
Calculating Hamiltonian 39 of 46 averages with 50 trajectories
Calculating Hamiltonian 40 of 46 averages with 50 trajectories
Calculating Hamiltonian 41 of 46 averages with 50 trajectories
Calculating Hamiltonian 42 of 46 averages with 50 trajectories
Calculating Hamiltonian 43 of 46 averages with 50 trajectories
Calculating Hamiltonian 44 of 46 averages with 50 trajectories
Calculating Hamiltonian 3 of 41 averages with 50 trajectories
Calculating Hamiltonian 45 of 46 averages with 50 trajectories
Calculating spectra for 0 of 92046 averages
Calculating spectra for 1000 of 92046 averages
Calculating spectra for 2000 of 92046 averages
Calculating spectra for 3000 of 92046 averages
Calculating spectra for 4000 of 92046 averages
Calculating spectra for 5000 of 92046 averages
Calculating spectra for 6000 of 92046 averages
Calculating spectra for 7000 of 92046 averages
Calculating spectra for 8000 of 92046 averages
Calculating spectra for 9000 of 92046 averages
Calculating spectra for 10000 of 92046 averages
Calculating spectra for 11000 of 92046 averages
Calculating spectra for 12000 of 92046 averages
Calculating spectra for 13000 of 92046 averages
Calculating spectra for 14000 of 92046 averages
Calculating spectra for 15000 of 92046 averages
Calculating spectra for 16000 of 92046 averages
Calculating spectra for 17000 of 92046 averages
Calculating spectra for 18000 of 92046 averages
Calculating spectra for 19000 of 92046 averages
Calculating spectra for 20000 of 92046 averages
Calculating spectra for 21000 of 92046 averages
Calculating spectra for 22000 of 92046 averages
Calculating spectra for 23000 of 92046 averages
Calculating spectra for 24000 of 92046 averages
Calculating spectra for 25000 of 92046 averages
Calculating spectra for 26000 of 92046 averages
Calculating spectra for 27000 of 92046 averages
Calculating spectra for 28000 of 92046 averages
Calculating spectra for 29000 of 92046 averages
Calculating spectra for 30000 of 92046 averages
Calculating spectra for 31000 of 92046 averages
Calculating spectra for 32000 of 92046 averages
Calculating spectra for 33000 of 92046 averages
Calculating spectra for 34000 of 92046 averages
Calculating spectra for 35000 of 92046 averages
Calculating spectra for 36000 of 92046 averages
Calculating spectra for 37000 of 92046 averages
Calculating spectra for 38000 of 92046 averages
Calculating spectra for 39000 of 92046 averages
Calculating spectra for 40000 of 92046 averages
Calculating spectra for 41000 of 92046 averages
Calculating spectra for 42000 of 92046 averages
Calculating spectra for 43000 of 92046 averages
Calculating spectra for 44000 of 92046 averages
Calculating spectra for 45000 of 92046 averages
Calculating spectra for 46000 of 92046 averages
Calculating spectra for 47000 of 92046 averages
Calculating spectra for 48000 of 92046 averages
Calculating spectra for 49000 of 92046 averages
Calculating spectra for 50000 of 92046 averages
Calculating spectra for 51000 of 92046 averages
Calculating spectra for 52000 of 92046 averages
Calculating spectra for 53000 of 92046 averages
Calculating spectra for 54000 of 92046 averages
Calculating spectra for 55000 of 92046 averages
Calculating spectra for 56000 of 92046 averages
Calculating spectra for 57000 of 92046 averages
Calculating spectra for 58000 of 92046 averages
Calculating spectra for 59000 of 92046 averages
Calculating spectra for 60000 of 92046 averages
Calculating spectra for 61000 of 92046 averages
Calculating spectra for 62000 of 92046 averages
Calculating spectra for 63000 of 92046 averages
Calculating spectra for 64000 of 92046 averages
Calculating spectra for 65000 of 92046 averages
Calculating spectra for 66000 of 92046 averages
Calculating spectra for 67000 of 92046 averages
Calculating spectra for 68000 of 92046 averages
Calculating spectra for 69000 of 92046 averages
Calculating spectra for 70000 of 92046 averages
Calculating spectra for 71000 of 92046 averages
Calculating spectra for 72000 of 92046 averages
Calculating spectra for 73000 of 92046 averages
Calculating spectra for 74000 of 92046 averages
Calculating spectra for 75000 of 92046 averages
Calculating spectra for 76000 of 92046 averages
Calculating spectra for 77000 of 92046 averages
Calculating spectra for 78000 of 92046 averages
Calculating spectra for 79000 of 92046 averages
Calculating spectra for 80000 of 92046 averages
Calculating spectra for 81000 of 92046 averages
Calculating spectra for 82000 of 92046 averages
Calculating spectra for 83000 of 92046 averages
Calculating spectra for 84000 of 92046 averages
Calculating spectra for 85000 of 92046 averages
Calculating spectra for 86000 of 92046 averages
Calculating spectra for 87000 of 92046 averages
Calculating spectra for 88000 of 92046 averages
Calculating spectra for 89000 of 92046 averages
Calculating spectra for 90000 of 92046 averages
Calculating spectra for 91000 of 92046 averages
Calculating spectra for 92000 of 92046 averages
Calculating Hamiltonian 4 of 41 averages with 50 trajectories
Calculating Hamiltonian 5 of 41 averages with 50 trajectories
Calculating Hamiltonian 6 of 41 averages with 50 trajectories
Calculating Hamiltonian 7 of 41 averages with 50 trajectories
Calculating Hamiltonian 8 of 41 averages with 50 trajectories
Calculating Hamiltonian 9 of 41 averages with 50 trajectories
Calculating Hamiltonian 10 of 41 averages with 50 trajectories
Calculating Hamiltonian 11 of 41 averages with 50 trajectories
Calculating Hamiltonian 12 of 41 averages with 50 trajectories
Calculating Hamiltonian 13 of 41 averages with 50 trajectories
Calculating Hamiltonian 14 of 41 averages with 50 trajectories
Calculating Hamiltonian 15 of 41 averages with 50 trajectories
Calculating Hamiltonian 16 of 41 averages with 50 trajectories
Calculating Hamiltonian 17 of 41 averages with 50 trajectories
Calculating Hamiltonian 18 of 41 averages with 50 trajectories
Calculating Hamiltonian 19 of 41 averages with 50 trajectories
