 Read checkpoint file S_1.chk type G16
 Write formatted file S_1.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 15:22:41 2023
 Aft UFChkP           Thu Jan 26 15:27:01 2023      260.28 cpu,      260.29 elapsed
 Aft DecCub           Thu Jan 26 15:27:12 2023       10.57 cpu,       10.57 elapsed
 Aft Density          Thu Jan 26 15:27:12 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 15:27:12 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4501457010
 Aft DoCube           Thu Jan 26 15:27:29 2023       17.39 cpu,       17.44 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 15:27:29 2023
 Aft UFChkP           Thu Jan 26 15:31:51 2023      261.39 cpu,      261.41 elapsed
 Aft DecCub           Thu Jan 26 15:32:01 2023       10.66 cpu,       10.66 elapsed
 Aft Density          Thu Jan 26 15:32:01 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 15:32:02 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3867980007
 Aft DoCube           Thu Jan 26 15:32:19 2023       17.27 cpu,       17.27 elapsed
 Read checkpoint file S_2.chk type G16
 Write formatted file S_2.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 15:32:40 2023
 Aft UFChkP           Thu Jan 26 15:37:03 2023      262.84 cpu,      262.85 elapsed
 Aft DecCub           Thu Jan 26 15:37:13 2023       10.81 cpu,       10.82 elapsed
 Aft Density          Thu Jan 26 15:37:13 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 15:37:14 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4500035512
 Aft DoCube           Thu Jan 26 15:37:31 2023       17.29 cpu,       17.29 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 15:37:31 2023
 Aft UFChkP           Thu Jan 26 15:41:51 2023      260.56 cpu,      260.58 elapsed
 Aft DecCub           Thu Jan 26 15:42:02 2023       10.60 cpu,       10.60 elapsed
 Aft Density          Thu Jan 26 15:42:02 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 15:42:02 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3813304348
 Aft DoCube           Thu Jan 26 15:42:19 2023       17.30 cpu,       17.34 elapsed
 Read checkpoint file S_3.chk type G16
 Write formatted file S_3.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 15:42:40 2023
 Aft UFChkP           Thu Jan 26 15:47:01 2023      260.32 cpu,      260.35 elapsed
 Aft DecCub           Thu Jan 26 15:47:11 2023       10.62 cpu,       10.61 elapsed
 Aft Density          Thu Jan 26 15:47:11 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 15:47:11 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4511927873
 Aft DoCube           Thu Jan 26 15:47:29 2023       17.28 cpu,       17.30 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 15:47:29 2023
 Aft UFChkP           Thu Jan 26 15:51:49 2023      260.62 cpu,      260.64 elapsed
 Aft DecCub           Thu Jan 26 15:52:00 2023       10.66 cpu,       10.66 elapsed
 Aft Density          Thu Jan 26 15:52:00 2023        0.01 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 15:52:00 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3863288099
 Aft DoCube           Thu Jan 26 15:52:17 2023       17.28 cpu,       17.29 elapsed
 Read checkpoint file S_4.chk type G16
 Write formatted file S_4.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 15:52:38 2023
 Aft UFChkP           Thu Jan 26 15:57:00 2023      261.58 cpu,      261.61 elapsed
 Aft DecCub           Thu Jan 26 15:57:11 2023       10.66 cpu,       10.67 elapsed
 Aft Density          Thu Jan 26 15:57:11 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 15:57:11 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4495589068
 Aft DoCube           Thu Jan 26 15:57:28 2023       17.26 cpu,       17.29 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 15:57:28 2023
 Aft UFChkP           Thu Jan 26 16:01:48 2023      260.15 cpu,      260.17 elapsed
 Aft DecCub           Thu Jan 26 16:01:59 2023       10.64 cpu,       10.64 elapsed
 Aft Density          Thu Jan 26 16:01:59 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:01:59 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3813192336
 Aft DoCube           Thu Jan 26 16:02:16 2023       17.28 cpu,       17.34 elapsed
 Read checkpoint file S_5.chk type G16
 Write formatted file S_5.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:02:37 2023
 Aft UFChkP           Thu Jan 26 16:06:59 2023      261.40 cpu,      261.46 elapsed
 Aft DecCub           Thu Jan 26 16:07:09 2023       10.65 cpu,       10.65 elapsed
 Aft Density          Thu Jan 26 16:07:09 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:07:10 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4488004997
 Aft DoCube           Thu Jan 26 16:07:27 2023       17.20 cpu,       17.19 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:07:27 2023
 Aft UFChkP           Thu Jan 26 16:11:48 2023      260.93 cpu,      261.02 elapsed
 Aft DecCub           Thu Jan 26 16:11:58 2023       10.64 cpu,       10.64 elapsed
 Aft Density          Thu Jan 26 16:11:58 2023        0.01 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:11:59 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3559415512
 Aft DoCube           Thu Jan 26 16:12:16 2023       17.36 cpu,       17.46 elapsed
 Read checkpoint file S_6.chk type G16
 Write formatted file S_6.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:12:37 2023
 Aft UFChkP           Thu Jan 26 16:16:58 2023      261.00 cpu,      261.05 elapsed
 Aft DecCub           Thu Jan 26 16:17:09 2023       10.61 cpu,       10.61 elapsed
 Aft Density          Thu Jan 26 16:17:09 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:17:09 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4488156081
 Aft DoCube           Thu Jan 26 16:17:26 2023       17.38 cpu,       17.38 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:17:26 2023
 Aft UFChkP           Thu Jan 26 16:21:52 2023      265.32 cpu,      265.40 elapsed
 Aft DecCub           Thu Jan 26 16:22:02 2023       10.65 cpu,       10.65 elapsed
 Aft Density          Thu Jan 26 16:22:02 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:22:03 2023        0.14 cpu,        0.14 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3565874276
 Aft DoCube           Thu Jan 26 16:22:20 2023       17.27 cpu,       17.26 elapsed
 Read checkpoint file S_7.chk type G16
 Write formatted file S_7.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:22:41 2023
 Aft UFChkP           Thu Jan 26 16:27:03 2023      261.20 cpu,      261.28 elapsed
 Aft DecCub           Thu Jan 26 16:27:13 2023       10.63 cpu,       10.63 elapsed
 Aft Density          Thu Jan 26 16:27:13 2023        0.01 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:27:13 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4494651279
 Aft DoCube           Thu Jan 26 16:27:31 2023       17.26 cpu,       17.27 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:27:31 2023
 Aft UFChkP           Thu Jan 26 16:31:52 2023      261.34 cpu,      261.43 elapsed
 Aft DecCub           Thu Jan 26 16:32:03 2023       10.67 cpu,       10.68 elapsed
 Aft Density          Thu Jan 26 16:32:03 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:32:03 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3799475347
 Aft DoCube           Thu Jan 26 16:32:20 2023       17.26 cpu,       17.26 elapsed
 Read checkpoint file S_8.chk type G16
 Write formatted file S_8.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:32:42 2023
 Aft UFChkP           Thu Jan 26 16:37:05 2023      261.01 cpu,      263.20 elapsed
 Aft DecCub           Thu Jan 26 16:37:15 2023       10.62 cpu,       10.63 elapsed
 Aft Density          Thu Jan 26 16:37:15 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:37:15 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4485995130
 Aft DoCube           Thu Jan 26 16:37:33 2023       17.31 cpu,       17.39 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:37:33 2023
 Aft UFChkP           Thu Jan 26 16:41:54 2023      260.63 cpu,      260.67 elapsed
 Aft DecCub           Thu Jan 26 16:42:04 2023       10.63 cpu,       10.63 elapsed
 Aft Density          Thu Jan 26 16:42:04 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:42:04 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3663679907
 Aft DoCube           Thu Jan 26 16:42:22 2023       17.41 cpu,       17.47 elapsed
 Read checkpoint file S_9.chk type G16
 Write formatted file S_9.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:42:44 2023
 Aft UFChkP           Thu Jan 26 16:47:09 2023      262.92 cpu,      264.86 elapsed
 Aft DecCub           Thu Jan 26 16:47:19 2023       10.68 cpu,       10.69 elapsed
 Aft Density          Thu Jan 26 16:47:19 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:47:19 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4491129029
 Aft DoCube           Thu Jan 26 16:47:37 2023       17.27 cpu,       17.28 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:47:37 2023
 Aft UFChkP           Thu Jan 26 16:51:58 2023      260.94 cpu,      261.42 elapsed
 Aft DecCub           Thu Jan 26 16:52:09 2023       10.63 cpu,       10.64 elapsed
 Aft Density          Thu Jan 26 16:52:09 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:52:12 2023        0.08 cpu,        2.79 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3803360402
 Aft DoCube           Thu Jan 26 16:52:29 2023       17.26 cpu,       17.31 elapsed
 Read checkpoint file S_10.chk type G16
 Write formatted file S_10.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:53:57 2023
 Aft UFChkP           Thu Jan 26 16:58:22 2023      261.58 cpu,      264.55 elapsed
 Aft DecCub           Thu Jan 26 16:58:32 2023       10.67 cpu,       10.67 elapsed
 Aft Density          Thu Jan 26 16:58:32 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 16:58:33 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4493071371
 Aft DoCube           Thu Jan 26 16:58:50 2023       17.34 cpu,       17.34 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 16:58:50 2023
 Aft UFChkP           Thu Jan 26 17:03:12 2023      261.78 cpu,      261.83 elapsed
 Aft DecCub           Thu Jan 26 17:03:22 2023       10.66 cpu,       10.67 elapsed
 Aft Density          Thu Jan 26 17:03:22 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:03:22 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3846573625
 Aft DoCube           Thu Jan 26 17:03:40 2023       17.26 cpu,       17.26 elapsed
 Read checkpoint file S_11.chk type G16
 Write formatted file S_11.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:04:01 2023
 Aft UFChkP           Thu Jan 26 17:08:25 2023      262.19 cpu,      264.62 elapsed
 Aft DecCub           Thu Jan 26 17:08:36 2023       10.68 cpu,       10.69 elapsed
 Aft Density          Thu Jan 26 17:08:36 2023        0.01 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:08:36 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4489360317
 Aft DoCube           Thu Jan 26 17:08:53 2023       17.27 cpu,       17.28 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:08:59 2023
 Aft UFChkP           Thu Jan 26 17:13:20 2023      261.33 cpu,      261.42 elapsed
 Aft DecCub           Thu Jan 26 17:13:31 2023       10.65 cpu,       10.65 elapsed
 Aft Density          Thu Jan 26 17:13:31 2023        0.01 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:13:31 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3850019497
 Aft DoCube           Thu Jan 26 17:13:49 2023       17.43 cpu,       17.43 elapsed
 Read checkpoint file S_12.chk type G16
 Write formatted file S_12.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:14:10 2023
 Aft UFChkP           Thu Jan 26 17:18:36 2023      261.31 cpu,      265.23 elapsed
 Aft DecCub           Thu Jan 26 17:18:46 2023       10.64 cpu,       10.65 elapsed
 Aft Density          Thu Jan 26 17:18:46 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:21:06 2023        0.07 cpu,      139.40 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4713712201
 Aft DoCube           Thu Jan 26 17:21:23 2023       17.30 cpu,       17.88 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:21:24 2023
 Aft UFChkP           Thu Jan 26 17:25:45 2023      261.16 cpu,      261.22 elapsed
 Aft DecCub           Thu Jan 26 17:25:56 2023       10.61 cpu,       10.61 elapsed
 Aft Density          Thu Jan 26 17:25:56 2023        0.01 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:25:56 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3665852671
 Aft DoCube           Thu Jan 26 17:26:13 2023       17.28 cpu,       17.30 elapsed
 Read checkpoint file S_13.chk type G16
 Write formatted file S_13.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:26:37 2023
 Aft UFChkP           Thu Jan 26 17:31:01 2023      261.48 cpu,      263.84 elapsed
 Aft DecCub           Thu Jan 26 17:31:12 2023       10.65 cpu,       10.65 elapsed
 Aft Density          Thu Jan 26 17:31:12 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:31:12 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4721972712
 Aft DoCube           Thu Jan 26 17:31:29 2023       17.31 cpu,       17.32 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:31:29 2023
 Aft UFChkP           Thu Jan 26 17:35:51 2023      261.33 cpu,      261.58 elapsed
 Aft DecCub           Thu Jan 26 17:36:01 2023       10.66 cpu,       10.66 elapsed
 Aft Density          Thu Jan 26 17:36:01 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:36:02 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3669515992
 Aft DoCube           Thu Jan 26 17:36:19 2023       17.40 cpu,       17.46 elapsed
 Read checkpoint file S_14.chk type G16
 Write formatted file S_14.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:36:41 2023
 Aft UFChkP           Thu Jan 26 17:41:06 2023      261.57 cpu,      265.17 elapsed
 Aft DecCub           Thu Jan 26 17:41:16 2023       10.66 cpu,       10.66 elapsed
 Aft Density          Thu Jan 26 17:41:16 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:41:17 2023        0.07 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4727288368
 Aft DoCube           Thu Jan 26 17:41:34 2023       17.27 cpu,       17.28 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:41:34 2023
 Aft UFChkP           Thu Jan 26 17:46:01 2023      266.31 cpu,      266.65 elapsed
 Aft DecCub           Thu Jan 26 17:46:11 2023       10.85 cpu,       10.85 elapsed
 Aft Density          Thu Jan 26 17:46:11 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:46:11 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3666733320
 Aft DoCube           Thu Jan 26 17:46:29 2023       17.46 cpu,       17.45 elapsed
 Read checkpoint file S_15.chk type G16
 Write formatted file S_15.fchk
 FChkPn:  Coordinates translated and rotated.
 FChkPn:  Coordinates match /B/ after translation and rotation.
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:49:33 2023
 Aft UFChkP           Thu Jan 26 17:53:57 2023      261.07 cpu,      263.92 elapsed
 Aft DecCub           Thu Jan 26 17:54:07 2023       10.64 cpu,       10.64 elapsed
 Aft Density          Thu Jan 26 17:54:07 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:54:07 2023        0.06 cpu,        0.07 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.4491666067
 Aft DoCube           Thu Jan 26 17:54:25 2023       17.29 cpu,       17.29 elapsed
 Will use up to     4 threads.
 Top CubeGen          Thu Jan 26 17:54:25 2023
 Aft UFChkP           Thu Jan 26 17:58:46 2023      261.20 cpu,      261.24 elapsed
 Aft DecCub           Thu Jan 26 17:58:56 2023       10.60 cpu,       10.60 elapsed
 Aft Density          Thu Jan 26 17:58:56 2023        0.00 cpu,        0.00 elapsed
 Bef DoCube           Thu Jan 26 17:58:57 2023        0.07 cpu,        0.09 elapsed
 There are a total of     1669570 grid points.
 ElSum from         orbitals=        0.3641222050
 Aft DoCube           Thu Jan 26 17:59:14 2023       17.24 cpu,       17.30 elapsed
